-- POSDBA 생성
CREATE USER POSDBA IDENTIFIED BY "1234";

GRANT CREATE SESSION, DBA TO POSDBA;
commit;
-- DEV 생성
CREATE USER POSDEV1 IDENTIFIED BY "1234"; 
CREATE USER POSDEV2 IDENTIFIED BY "1234";
CREATE USER POSDEV3 IDENTIFIED BY "1234";
CREATE USER POSDEV4 IDENTIFIED BY "1234";

-- 세션권한
GRANT CREATE SESSION TO POSDEV1;
GRANT CREATE SESSION TO POSDEV2;
GRANT CREATE SESSION TO POSDEV3;
GRANT CREATE SESSION TO POSDEV4;

-- 권한부여 GRANT SELECT ON [TABLE NAME] TO [USER];
GRANT SELECT, INSERT, UPDATE ON ST TO POSDEV1;
GRANT SELECT, INSERT, UPDATE ON ST TO POSDEV2;
GRANT SELECT, INSERT, UPDATE ON ST TO POSDEV3;
GRANT SELECT, INSERT, UPDATE ON ST TO POSDEV4;

-- 테이블생성
CREATE TABLE CATEGORIES(
 CA_CODE NCHAR(2),
 CA_NAME NVARCHAR2(10)
 )TABLESPACE USERS;

CREATE TABLE ORDERS(
OS_STCODE NCHAR(10),
OS_DATE DATE,
OS_TYPE NCHAR(2),
OS_STATEMENT NCHAR(2)
)TABLESPACE USERS;

DROP TABLE ORDERS;

CREATE TABLE ORDERSDETAIL(
OD_ORSTCODE NCHAR(10),
OD_ORDATE DATE,
OD_SMCODE NCHAR(3),
OD_COUNT NUMBER(2,0)
)TABLESPACE USERS;

CREATE TABLE SALES(
SA_STCODE NCHAR(10),
SA_DATE DATE,
SA_PAYMENTTYPE NCHAR(2),
SA_ORTIME DATE,
SA_PRICE NUMBER(1,0)
)TABLESPACE USERS;

CREATE TABLE STORE(
ST_ID	NVARCHAR2(50),
ST_NAME	NVARCHAR2(5),
ST_EMAIL	NVARCHAR2(50),
ST_JOINDATE	DATE,
ST_CODE	NCHAR(10),
ST_STNAME NVARCHAR2(50),
ST_INFO	NVARCHAR2(30),
ST_INFODETAIL	NVARCHAR2(2000),
ST_PHONE	NCHAR(11),
ST_SICODE	NCHAR(14),
ST_SNSTYPE	NCHAR(2),
ST_CATEGORY	NCHAR(2)
)TABLESPACE USERS;

CREATE TABLE STOREMENU(
SM_STCODE	NCHAR(10),
SM_CODE	NCHAR(3),
SM_NAME	NVARCHAR2(10),
SM_PRICE	NUMBER(5, 0),
SM_SICODE	NCHAR(14),
SM_ISMAIN	NCHAR(1),
SM_ISKIOSK	NCHAR(1),
SM_ISSOLD	NCHAR(1),
SM_ISDELETE	NCHAR(1)
)TABLESPACE USERS;

CREATE TABLE LOCATION(
LO_STCODE	NCHAR(10),
LO_CODE	NCHAR(3),
LO_NAME	NVARCHAR2(10),
LO_LATITUDE	NUMBER(18,10),
LO_LONGITUDE	NUMBER(18,10)
)TABLESPACE USERS;

CREATE TABLE STOREIMAGE(
SI_CODE	NCHAR(14),
SI_NAME	NCHAR(20)
)TABLESPACE USERS;

CREATE TABLE ACCESSLOG(
AL_STCODE	NCHAR(10),
AL_DATE	DATE,
AL_TYPE	NCHAR(1),
AL_IP	NVARCHAR2(15)
)TABLESPACE USERS;

CREATE TABLE SALESLOG(
SL_STCODE	NCHAR(10),
SL_LOCODE	NVARCHAR2(100),
SL_STATE	NCHAR(2),
SL_DATE	DATE,
SL_ALDATE	DATE
)TABLESPACE USERS;

CREATE TABLE SCHEDULE(
SC_STCODE	NCHAR(10),
SC_STARTDATE	DATE,
SC_ENDDATE	DATE,
SC_STARTTIME DATE,
SC_ENDTIME	DATE,
SC_LOCODE	NVARCHAR2(100)
)TABLESPACE USERS;

CREATE TABLE ACCESSLOGTEMP(
AT_STID NCHAR(10),
AT_ALDATE	DATE,
AT_ALTYPE	NCHAR(1),
AT_ALIP	NVARCHAR2(15)
)TABLESPACE USERS;
DROP TABLE ACCESSLOGTEMP;
--테이블 생성

-- SYNONYM 생성
CREATE PUBLIC SYNONYM CA FOR CATEGORIES;
CREATE PUBLIC SYNONYM OS FOR ORDERS;
CREATE PUBLIC SYNONYM OD FOR ORDERSDETAIL;
CREATE PUBLIC SYNONYM SA FOR SALES;
CREATE PUBLIC SYNONYM ST FOR STORE;
CREATE PUBLIC SYNONYM SM FOR STOREMENU;
CREATE PUBLIC SYNONYM LO FOR LOCATION;
CREATE PUBLIC SYNONYM SI FOR STOREIMAGE;
CREATE PUBLIC SYNONYM AL FOR ACCESSLOG;
CREATE PUBLIC SYNONYM SL FOR SALESLOG;
CREATE PUBLIC SYNONYM OD FOR ORDERSDETAIL;
CREATE PUBLIC SYNONYM SC FOR SCHEDULE;
CREATE PUBLIC SYNONYM AT FOR ACCESSLOGTEMP;
-- SYNONYM 생성

SELECT *
FROM STORE;
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('SN','분식');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('SW','샌드위치');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('DE','디저트');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('MS','메시칸');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('AS','아시아');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('IT','이탈리안');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('DR','커피/음료');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('SE','씨푸드');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('KA','카카오');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('NA','네이버');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('OP','영업중');
INSERT INTO CATEGORIES(CA_CODE,CA_NAME)
VALUES('CL','영업종료');

INSERT INTO SALESLOG(SL_STATE)
VALUES('시작');



SELECT*
FROM CA;

-- 제약조건

-- UK
ALTER TABLE STORE ADD CONSTRAINT UK_SNSID_EMAIL UNIQUE(ST_SNSID, ST_EMAIL);
-- PK
ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CA_CODE PRIMARY KEY(CA_CODE);
ALTER TABLE ORDERS ADD CONSTRAINT PK_OS_STCODE PRIMARY KEY(OS_STCODE);
ALTER TABLE ORDERS ADD CONSTRAINT PK_OS_DATE PRIMARY KEY(OS_DATE);
ALTER TABLE ORDERSDETAIL ADD CONSTRAINT PK_OD_OSSTCODE_OSDATE_SMCODE PRIMARY KEY(OD_OSSTCODE, OD_OSDATE, OD_SMCODE);
ALTER TABLE SALES ADD CONSTRAINT PK_SA_STCODE_DATE PRIMARY KEY (SA_STCODE, SA_DATE);
ALTER TABLE STORE ADD CONSTRAINT PK_ST_CODE PRIMARY KEY (ST_CODE);
ALTER TABLE STOREMENU ADD CONSTRAINT PK_SM_STCODE_CODE PRIMARY KEY(SM_STCODE, SM_CODE);
ALTER TABLE LOCATION ADD CONSTRAINT PK_LO_STCODE_CODE PRIMARY KEY(LO_STCODE, LO_CODE);
ALTER TABLE STOREIMAGE ADD CONSTRAINT PK_SI_CODE PRIMARY KEY(SI_CODE);
ALTER TABLE ACCESSLOG ADD CONSTRAINT PK_AL_SNSID_DATE PRIMARY KEY(AL_SNSID, AL_DATE);
ALTER TABLE SALESLOG ADD CONSTRAINT PK_SL_STCODE_DATE PRIMARY KEY(SL_STCODE, SL_DATE);
ALTER TABLE SCHEDULE ADD CONSTRAINT PK_SC_STCODE_STARTDATE_ENDDATE PRIMARY KEY(SC_STCODE, SC_STARTDATE, SC_ENDDATE);
-- FK
ALTER TABLE STORE ADD CONSTRAINT FK_ST_SICODE FOREIGN KEY (ST_SICODE) REFERENCES STOREIMAGE(SI_CODE);
ALTER TABLE STORE ADD CONSTRAINT FK_ST_SNSTYPE FOREIGN KEY (ST_SNSTYPE) REFERENCES CATEGORIES(CA_CODE);
ALTER TABLE STOREMENU ADD CONSTRAINT FK_SM_STCODE FOREIGN KEY(SM_STCODE) REFERENCES STORE(ST_CODE);
ALTER TABLE STOREMENU ADD CONSTRAINT FK_SM_STCODE FOREIGN KEY(SM_SICODE) REFERENCES STOREIMAGE(SI_CODE);
ALTER TABLE ORDERS ADD CONSTRAINT FK_OS_STCODE FOREIGN KEY(OS_STCODE) REFERENCES STORE(ST_CODE);
ALTER TABLE ORDERSDETAIL ADD CONSTRAINT FK_OD_OSSTCODE_DATE FOREIGN KEY(OD_OSSTCODE, OD_OSDATE) REFERENCES ORDERS(OS_STCODE, OS_DATE);
ALTER TABLE ORDERSDETAIL ADD CONSTRAINT FK_OD_SMCODE FOREIGN KEY(OD_SMCODE) REFERENCES STOREMENU(SM_CODE);
-- DF

-- NN

ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CA_CODE PRIMARY KEY(CA_CODE);
ALTER TABLE ORDERS ADD CONSTRAINT PK_OS_STCODE_DATE PRIMARY KEY(OS_STCODE, OS_DATE);
ALTER TABLE ORDERSDETAIL ADD CONSTRAINT PK_OD_ORSTCODE_ORDATE_SMCODE PRIMARY KEY(OD_ORSTCODE, OD_ORDATE, OD_SMCODE);
ALTER TABLE SALES ADD CONSTRAINT PK_SA_STCODE_DATE PRIMARY KEY(SA_STCODE,SA_DATE);
ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CA_CODE PRIMARY KEY(CA_CODE);
ALTER TABLE STORE ADD CONSTRAINT PK_ST_CODE PRIMARY KEY(ST_CODE);
ALTER TABLE STOREMENU ADD CONSTRAINT PK_SM_STCODE_CODE PRIMARY KEY(SM_STCODE,SM_CODE);
ALTER TABLE LOCATION ADD CONSTRAINT PK_LO_STCODE_CODE PRIMARY KEY(LO_STCODE,LO_CODE);
ALTER TABLE STOREIMAGE ADD CONSTRAINT PK_SI_CODE PRIMARY KEY(SI_CODE);
ALTER TABLE ACCESSLOG ADD CONSTRAINT PK_AL_STCODE_DATE PRIMARY KEY(AL_STCODE,AL_DATE);
ALTER TABLE SALESLOG ADD CONSTRAINT PK_SL_STCODE_DATE PRIMARY KEY(SL_STCODE,SL_DATE);
ALTER TABLE SCHEDULE ADD CONSTRAINT PK_SC_STCODE_STARTDATE_ENDDATE PRIMARY KEY(SC_STCODE, SC_STARTDATE, SC_ENDDATE);
ALTER TABLE ACCESSLOGTEMP ADD CONSTRAINT PK_AT_STID PRIMARY KEY(AT_STID);

ALTER TABLE ORDERS ADD CONSTRAINT FK_OS_STCODE FOREIGN KEY(OS_STCODE)REFERENCES STORE(ST_CODE);
ALTER TABLE ORDERS ADD CONSTRAINT FK_OS_TYPE FOREIGN KEY(OS_TYPE)REFERENCES CATEGORIES(CA_CODE);
ALTER TABLE ORDERS ADD CONSTRAINT FK_OS_TYPE FOREIGN KEY(OS_TYPE)REFERENCES CATEGORIES(CA_CODE);

ALTER TABLE ORDERSDETAIL ADD CONSTRAINT FK_OD_ORSTCODE_ORDATE FOREIGN KEY (OD_ORSTCODE_DATE) REFERENCES ORDERS(OS_STCODE, OS_DATE);
ALTER TABLE ACCESSLOGTEMP ADD CONSTRAINT FK_AT_STID FOREIGN KEY(AT_STID) REFERENCES STORE(ST_ID);
ALTER TABLE ACCESSLOG RENAME COLUMN AL_STCODE TO AL_STID;
ALTER TABLE SALESLOG DROP COLUMN SL_ALDATE;
ALTER TABLE STORE ADD CONSTRAINT FK_ST_SICODE FOREIGN KEY(ST_SICODE) REFERENCES STOREIMAGE(SI_CODE);
ALTER TABLE STORE ADD CONSTRAINT FK_ST_SNSTYPE FOREIGN KEY(ST_SNSTYPE) REFERENCES CATEGORIES(CA_CODE);

ALTER TABLE ACCESSLOG MODIFY AL_STID NVARCHAR2(50);
ALTER TABLE STORE RENAME COLUMN ST_ID TO ST_SNSID;
ALTER TABLE ACCESSLOG RENAME COLUMN AL_STID TO AL_SNSID;
ALTER TABLE STORE ADD CONSTRAINT PK_ST_SNSID PRIMARY KEY(ST_SNSID);

ALTER TABLE ACCESSLOG DROP CONSTRAINT PK_AL_STSNSID_DATE;
ALTER TABLE ACCESSLOG ADD CONSTRAINT PK_AL_SNSID_DATE PRIMARY KEY(AL_SNSID, AL_DATE);
ALTER TABLE ACCESSLOG RENAME COLUMN AL_STSNSID TO AL_SNSID;

ALTER TABLE ACCESSLOG ADD CONSTRAINT FK_AL_STSNSID FOREIGN KEY(AL_STSNSID) REFERENCES STORE(ST_SNSID);

ALTER TABLE SALESLOG ADD CONSTRAINT PK_SL_STCODE_DATE PRIMARY KEY(SL_STCODE, SL_DATE);
ALTER TABLE SALESLOG ADD CONSTRAINT FK_SL_STCODE FOREIGN KEY(SL_STCODE) REFERENCES STORE(ST_CODE);
ALTER TABLE SALESLOG RENAME COLUMN SL_ALDATE TO SL_DATE;
ALTER TABLE SALESLOG DROP CONSTRAINT PK_SL_STCODE_DATE;

ALTER TABLE SCHEDULE ADD CONSTRAINT FK_SC_STCODE FOREIGN KEY(SC_STCODE) REFERENCES STORE(ST_CODE);
ALTER TABLE SCHEDULE ADD CONSTRAINT FK_SC_LOCODE FOREIGN KEY(SC_LOCODE) REFERENCES LOCATION(LO_CODE);
ALTER TABLE SCHEDULE MODIFY SC_LOCODE NCHAR(3);
COMMIT;

ALTER TABLE STORE MODIFY ST_NAME NVARCHAR2(20) NOT NULL;
ALTER TABLE [테이블명] MODIFY ([컬럼명] DEFAULT [설정할 DEFAULT]);
ALTER TABLE STORE MODIFY ST_JOINDATE DEFAULT SYSDATE;
ALTER TABLE STORE MODIFY ST_JOINDATE DATE NOT NULL;
ALTER TABLE STORE MODIFY ST_STNAME NVARCHAR2(50) NOT NULL;
ALTER TABLE STORE MODIFY ST_SNSTYPE NCHAR(2) NOT NULL;
ALTER TABLE ORDERSDETAIL DROP CONSTRAINT PK_OD_ORSTCODE_ORDATE_SMCODE;
ALTER TABLE ORDERSDETAIL RENAME COLUMN OD_ORSTCODE TO OD_OSSTCODE;
ALTER TABLE ORDERSDETAIL ADD CONSTRAINT OD_OSSTCODE_OSDATE_SMCODE PRIMARY KEY(OD_OSSTCODE, OD_OSDATE, OD_SMCODE);
ALTER TABLE ORDERSDETAIL ADD CONSTRAINT FK_OD_OSSTCODE FOREIGN KEY (OD_OSSTCODE) REFERENCES STORE(ST_CODE);
ALTER TABLE ORDERSDETAIL ADD CONSTRAINT FK_OD_OSDATE FOREIGN KEY(OD_OSDATE) REFERENCES ORDERS(OS_DATE);
ALTER TABLE ORDERSDETAIL ADD CONSTRAINT FK_OD_SMCODE FOREIGN KEY(OD_SMCODE) REFERENCES STOREMENU(SM_CODE);
ALTER TABLE SALES ADD CONSTRAINT FK_SA_STCODE FOREIGN KEY(SA_STCODE) REFERENCES STORE(ST_CODE);
ALTER TABLE SALES ADD CONSTRAINT FK_SA_ODOSDATE FOREIGN KEY(SA_ODOSDATE) REFERENCES ORDERSDETAIL(OD_OSDATE);

-- 수정 기본형태 ALTER TABLE 테이블명 MODIFY 컬럼조건; 

-- 제약조건
SELECT ST_CODE
FROM STORE
WHERE ST_ID = '1234' AND ST_SNSTYPE = 'KA';


-- DB수정
ALTER TABLE STORE MODIFY(ST_NAME NVARCHAR2(20));